theme: minima
title: Twiggysoro
author: Twiggysoro
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 learning how to use GitHub for the first time

# social links
twitter_username: your-twitter-handle twiggysoro1
github_username:  your-github-handle twiggysoro

show_excerpts: true # set to false to remove excerpts on the homepage
